//
//  ElGamalCiphertext.c
//  VVK

#include "ElGamalCiphertext.h"
#include <openssl/x509.h>

ASN1_SEQUENCE(ELGAMAL_MODP_CIPHERTEXT) = {
    ASN1_SIMPLE(ELGAMAL_MODP_CIPHERTEXT, uBlind, ASN1_INTEGER),
    ASN1_SIMPLE(ELGAMAL_MODP_CIPHERTEXT, vBlindedMsg, ASN1_INTEGER),
} ASN1_SEQUENCE_END(ELGAMAL_MODP_CIPHERTEXT)

ASN1_SEQUENCE(ELGAMAL_MODP_CIPHER) = {
    ASN1_SIMPLE(ELGAMAL_MODP_CIPHER, alg, X509_ALGOR),
    ASN1_SIMPLE(ELGAMAL_MODP_CIPHER, cipher, ELGAMAL_MODP_CIPHERTEXT),
} ASN1_SEQUENCE_END(ELGAMAL_MODP_CIPHER)

ASN1_SEQUENCE(ELGAMAL_ECC_CIPHERTEXT) = {
    ASN1_SIMPLE(ELGAMAL_ECC_CIPHERTEXT, uBlind, ASN1_OCTET_STRING),
    ASN1_SIMPLE(ELGAMAL_ECC_CIPHERTEXT, vBlindedMsg, ASN1_OCTET_STRING),
} ASN1_SEQUENCE_END(ELGAMAL_ECC_CIPHERTEXT)

ASN1_SEQUENCE(ELGAMAL_ECC_CIPHER) = {
    ASN1_SIMPLE(ELGAMAL_ECC_CIPHER, alg, X509_ALGOR),
    ASN1_SIMPLE(ELGAMAL_ECC_CIPHER, cipher, ELGAMAL_ECC_CIPHERTEXT),
} ASN1_SEQUENCE_END(ELGAMAL_ECC_CIPHER)

IMPLEMENT_ASN1_FUNCTIONS(ELGAMAL_MODP_CIPHERTEXT)
IMPLEMENT_ASN1_FUNCTIONS(ELGAMAL_MODP_CIPHER)

IMPLEMENT_ASN1_FUNCTIONS(ELGAMAL_ECC_CIPHERTEXT)
IMPLEMENT_ASN1_FUNCTIONS(ELGAMAL_ECC_CIPHER)
